🔨 Add podClean gradle task
This resolves the following error which happened every time the pod version was changed.

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':composeApp:podInstall'.

Caused by: java.lang.IllegalStateException: 'pod install' command failed with code 1.
Error message:
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "DittoObjC":
  In snapshot (Podfile.lock):
    DittoObjC (= 4.7.2-rc.1)
  In Podfile:
    composeApp (from `../composeApp`) was resolved to 1.0, which depends on
      DittoObjC (= 4.7.1)